name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B -f eva4/pom.xml clean compile

    - name: Run tests with surefire report
      run: mvn -B -f eva4/pom.xml test surefire-report:report

    - name: Upload Surefire HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report
        path: eva4/target/site/surefire-report.html

    - name: SonarQube Scan
      if: ${{ env.SONAR_TOKEN != '' && env.SONAR_HOST_URL != '' }}
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: eva4
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      continue-on-error: true

    - name: Notify on failure
      if: failure() && env.SMTP_USERNAME != '' && env.SMTP_PASSWORD != '' && env.ALERT_EMAIL != '' && env.ALERT_FROM != ''
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "[CI] Fallo en pruebas Maven"
        to: ${{ secrets.ALERT_EMAIL }}
        from: ${{ secrets.ALERT_FROM }}
        body: |
          Las pruebas Maven han fallado en el repositorio ${{ github.repository }}.
          Revisa el reporte adjunto en la ejecución de GitHub Actions.
      continue-on-error: true
