name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B clean compile

    - name: Run tests with surefire report
      run: mvn -B test surefire-report:report

    - name: Upload Surefire HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report
        path: target/site/surefire-report.html

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Notify on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "[CI] Fallo en pruebas Maven"
        to: ${{ secrets.ALERT_EMAIL }}
        from: ${{ secrets.ALERT_EMAIL }}
        body: |
          Las pruebas Maven han fallado en el repositorio ${{ github.repository }}.
          Revisa el reporte adjunto en la ejecución de GitHub Actions.
